version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::086152674311:user/mandela"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::086152674311:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-3XKOHECWZ1EJ"
cloudformation_execution_role = "arn:aws:iam::086152674311:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-51XVD1BW423I"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-1pe3kemefwlvu"
image_repository = ""
region = "us-east-1"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::086152674311:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-51PQGH2O9H79"
cloudformation_execution_role = "arn:aws:iam::086152674311:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-YKEUONH7ZSYO"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-17h79jimggt03"
image_repository = ""
region = "us-east-2"
