version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::086152674311:user/mandela"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::086152674311:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-11SNOEWX4ICLB"
cloudformation_execution_role = "arn:aws:iam::086152674311:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-O6OFBQ94VVYU"
artifacts_bucket = "challenge5dev"
image_repository = ""
region = "us-east-2"
