AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Restaurant order-app 
  
Globals:
  Function:
    Timeout: 3

Resources:

  OrderTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: order-table
      AttributeDefinitions: 
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema: 
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  GetOrders:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: functions/get-orders/
      Handler: app.getOrders
      Runtime: nodejs14.x
      Environment:
        Variables:
          ORDER_TABLE: !Ref OrderTable
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:Query 
              - dynamodb:Scan
            Resource:
              - !Sub 
                - 'arn:aws:dynamodb:*:*:table/${Table}'
                - { Table: !Ref OrderTable }
          - Effect: Allow
            Action:
              - logs:*
            Resource:
              - "*"    
  OrderApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      Cors:
        AllowMethods: "'POST, GET, UPDATE, DELETE'"
        AllowHeaders: "'X-Forwarded-For'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: './api.yaml'

  ApiGwExecutionRole: 
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "apigateway.amazonaws.com"
                - "lambda.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"

  ApiGwExecutionPolicy: 
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: "apigw-execution-policy"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          Action:
            - lambda:*
          Effect: Allow
          Resource:
            - !GetAtt GetOrders.Arn
            - !GetAtt PostOrders.Arn
            - !GetAtt UpdateOrder.Arn
            - !GetAtt DeleteOrder.Arn
      Roles: 
        - Ref: "ApiGwExecutionRole"

  PostOrders:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: functions/post-orders/
      Handler: app.postOrders
      Runtime: nodejs14.x
      Environment:
        Variables:
          ORDER_TABLE: !Ref OrderTable
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:PutItem
            Resource:
              - !Sub 
                - 'arn:aws:dynamodb:*:*:table/${Table}'
                - { Table: !Ref OrderTable }
          - Effect: Allow
            Action:
              - logs:*
            Resource:
              - "*"    
  UpdateOrder:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: functions/update-order/
      Handler: app.updateOrder
      Runtime: nodejs14.x
      Environment:
        Variables:
          ORDER_TABLE: !Ref OrderTable
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:UpdateItem
            Resource:
              - !Sub 
                - 'arn:aws:dynamodb:*:*:table/${Table}'
                - { Table: !Ref OrderTable }
          - Effect: Allow
            Action:
              - logs:*
            Resource:
              - "*"    

  DeleteOrder:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: functions/delete-order/
      Handler: app.deleteOrder
      Runtime: nodejs14.x
      Environment:
        Variables:
          ORDER_TABLE: !Ref OrderTable
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:DeleteItem
            Resource:
              - !Sub 
                - 'arn:aws:dynamodb:*:*:table/${Table}'
                - { Table: !Ref OrderTable }
          - Effect: Allow
            Action:
              - logs:*
            Resource:
              - "*"    



Outputs:

  DynamoDBTableName:
    Description: "DynamoDB Table Name"
    Value: !Ref OrderTable

  GetOrders:
    Description: "GetOrders Lambda Function ARN"
    Value: !GetAtt GetOrders.Arn

  OrderApiEndpoint:
    Description: "API Gateway endpoint URL for Dev stage for Order Get function"
    Value: !Sub "https://${OrderApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/orders/"

  PostOrders:
    Description: "PostOrders Lambda Function ARN"
    Value: !GetAtt PostOrders.Arn

  UpdateOrder:
    Description: "UpdateOrder Lambda Function ARN"
    Value: !GetAtt UpdateOrder.Arn

  DeleteOrder:
    Description: "DeleteOrder Lambda Function ARN"
    Value: !GetAtt DeleteOrder.Arn
