AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  order-app

  Sample SAM Template for order-app
  
Globals:
  Function:
    Timeout: 3

Resources:

  OrderTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: order-table
      AttributeDefinitions: 
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema: 
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5


Outputs:

  DynamoDBTableName:
    Description: "DynamoDB Table Name"
    Value: !Ref OrderTable

